on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    runs-on: ubuntu-rust
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run linting on libhasher
        run: |
          cargo fmt --message-format human -- --check
          cargo check
          cargo clippy -q --no-deps -- -D warnings