on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-rust
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build the release
        run: |
          cargo build --release \
            --target x86_64-unknown-linux-musl \
            --target x86_64-pc-windows-gnu \
            --target aarch64-unknown-linux-musl \
            --target x86_64-apple-darwin \
            --target aarch64-apple-darwin
      
      - name: Generate the release folder
        run: |
          mkdir -p release
          cp ./target/x86_64-unknown-linux-musl/release/hasher release/hasher-linux-x86_64
          cp ./target/aarch64-unknown-linux-musl/release/hasher release/hasher-linux-aarch64
          cp ./target/x86_64-pc-windows-gnu/release/hasher.exe release/hasher-windows.exe
          cp ./target/aarch64-apple-darwin/release/hasher release/hasher-darwin-aarch64
          cp ./target/x86_64-apple-darwin/release/hasher release/hasher-darwin-x86_64
          cd release
          chmod +x hasher-linux-x86_64
          for file in *; do ./hasher-linux-x86_64 -a sha256 $file -o ${file}.sha256; done

      - name: Upload release binaries
        uses: actions/forgejo-release@v2.5.0
        with:
          url: "https://git.zevaryx.com"
          repo: "zevaryx/hasher-rs"
          direction: upload
          tag: "${{ github.ref_name }}"
          sha: "${{ github.sha }}"
          release-dir: release
          token: ${{ github.TOKEN }}