on:
  push:
    branches-ignore:
      - main
    tags-ignore:
      - '**'

jobs:
  test:
    runs-on: ubuntu-rust
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run tests on libhasher
        run: cargo test

      - name: Run tests on hasher
        run: cd hasher && cargo test