on:
  push:
    branches-ignore:
      - main
    tags-ignore:
      - '**'

jobs:
  test:
    runs-on: ubuntu-rust
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run tests
        run: cargo tarpaulin -o xml