on:
  push:
    branches-ignore:
      - main
    tags-ignore:
      - '**'

jobs:
  test:
    runs-on: ubuntu-rust
    container:
      image: ${{ secrets.CUSTOM_IMAGE_URL }}
      credentials:
        username: ${{ secrets.CUSTOM_IMAGE_USERNAME }}
        password: ${{ secrets.CUSTOM_IMAGE_PASSWORD }}
      options: "--security-opt seccomp=unconfined"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run tests
        run: cargo tarpaulin -o xml